# Generated by Django 5.0.1 on 2024-02-12 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("social", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="link",
            old_name="update",
            new_name="updated",
        ),
    ]
